theme: hugo-theme-m10c
defaultContentLanguage: en
enableRobotsTXT: yes
summaryLength: 0
pagination:
  pagerSize: 15
outputs:
  home:
    - HTML
    - RSS
    - JSON
privacy:
  vimeo:
    enableDNT: yes
  x:
    enableDNT: yes
  youTube:
    privacyEnhanced: yes
services:
  x:
    disableInlineCSS: yes
